c_compiler:            # [win]
  - clang              # [win]
c_compiler_version:    # [win]
  - 19                 # [win]
cxx_compiler:          # [win]
  - clangxx            # [win]
cxx_compiler_version:  # [win]
  - 19                 # [win]
