{% set name = "mimalloc" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/elbaro/mimalloc/archive/v{{ version }}.tar.gz
  url: https://github.com/elbaro/mimalloc/archive/refs/heads/fix/aligned-alloc.zip
  # sha256: a25c096dbd100b5f872bf458c080ebe539dbb8275c76e44e1f02b07341e6ca04
  sha256: 19aa831b511a0e1b670c5de9cec8513cb4be7e66db2f043891328b698aebefeb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("mimalloc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

# .
# ├── include
# │  ├── mimalloc-new-delete.h
# │  ├── mimalloc-override.h
# │  └── mimalloc.h
# └── lib
#    ├── libmimalloc.a
#    ├── libmimalloc.so -> libmimalloc.so.1.6
#    ├── libmimalloc.so.1.6
#    └── mimalloc.o

test:
  commands:
    - test -f $PREFIX/lib/libmimalloc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/mimalloc.h           # [unix]
    - if not exist %LIBRARY_PREFIX%\\bin\\mimalloc.dll exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\mimalloc.lib exit 1    # [win]
    - if not exist %LIBRARY_PREFIX%\\include\\mimalloc.h exit 1  # [win]

about:
  home: https://github.com/microsoft/mimalloc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: mimalloc is a compact general purpose allocator with excellent performance.

  description: |
    mimalloc (pronounced "me-malloc") is a general purpose allocator with
    excellent performance characteristics. Initially developed by Daan Leijen
    for the run-time systems of the Koka and Lean languages.
  dev_url: https://github.com/microsoft/mimalloc

extra:
  recipe-maintainers:
    - elbaro
    - xhochy
